const FIELDS=['routeId','codigo','fecha','nombre','origen','destino','localidad','empresa','tipoServicio','kmTotales','duracion','horaSalida','carreteras','peajes','importePeajes','tipoCarretera','dificultad','recomendable','valoracion','estado','itinerario','gasolineras','descansos','restaurantes','aparcamientos','paradas','interes','talleres','avisos','alternativa','consejos','notas'];
function $(id){return document.getElementById(id);}
function closeMenu(){sideMenu.classList.remove('open'); overlay.classList.remove('show'); sideMenu.setAttribute('aria-hidden','true');}
function openMenu(){sideMenu.classList.add('open'); overlay.classList.add('show'); sideMenu.setAttribute('aria-hidden','false');}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active')); $('view-'+name).classList.add('active'); closeMenu(); if(name==='list')renderList(); if(name==='config')loadConfigForm(); if(name==='sync')loadSyncForm(); if(name==='add'&&!routeId.value)prepareNewRoute();}
function prepareNewRoute(){routeForm.reset(); routeId.value=''; codigo.value=nextCode(); fecha.value=new Date().toISOString().slice(0,10); formTitle.textContent='Añadir ruta';}
function formToRoute(){const r={}; FIELDS.forEach(id=>{if(id==='routeId')return; r[id]=$(id).value;}); r.id=routeId.value||uid('RUTA'); r.codigo=codigo.value||nextCode(); return r;}
function routeToForm(r){FIELDS.forEach(id=>{const el=$(id); if(!el)return; if(id==='routeId')el.value=r.id||''; else el.value=r[id]??'';}); formTitle.textContent='Editar ruta '+(r.codigo||'');}
function editRoute(id){const r=getRoutes().find(x=>x.id===id); if(!r)return; routeToForm(r); showView('add');}
function handleSubmit(e){e.preventDefault(); upsertRoute(formToRoute()); alert('Ruta guardada correctamente.'); prepareNewRoute(); renderList(); showView('list'); syncNow(true);}
function bindEvents(){hamburgerBtn.onclick=openMenu; closeMenuBtn.onclick=closeMenu; overlay.onclick=closeMenu; document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view))); routeForm.addEventListener('submit',handleSubmit); clearFormBtn.onclick=prepareNewRoute; document.querySelectorAll('.filters input,.filters select').forEach(el=>el.addEventListener('input',renderList)); printFilteredBtn.onclick=printFiltered; copyExcelBtn.onclick=copyExcel; clearFiltersBtn.onclick=clearFilters; saveConfigBtn.onclick=saveConfigFromForm; resetConfigBtn.onclick=resetConfig; pairBtn.onclick=pairDevice; syncNowBtn.onclick=()=>syncNow(false); exportJsonBtn.onclick=downloadJSON; copyJsonBtn.onclick=copyJSON; restorePastedBtn.onclick=restoreFromText; importFileBtn.onclick=()=>importFileInput.click(); importFileInput.onchange=e=>{if(e.target.files[0])importFile(e.target.files[0]);}; window.addEventListener('routesChanged',()=>{renderList();updateKpis();});}
function init(){applyConfig(); bindEvents(); prepareNewRoute(); renderList(); loadSyncForm(); autoSyncOnStart();}
document.addEventListener('DOMContentLoaded',init);
