const DEFAULT_CONFIG={title:'Rutas María Jesús',theme:'verde',primary:'#15976b',secondary:'#0b5c99',font:'system',fontSize:16,menuOpacity:96,panelOpacity:94,mode:'claro'};
function getConfig(){return {...DEFAULT_CONFIG,...readJSON(STORE.CONFIG,{})};}
function saveConfig(cfg){writeJSON(STORE.CONFIG,{...getConfig(),...cfg}); applyConfig();}
function fontValue(v){return {system:'system-ui,-apple-system,Segoe UI,Arial,sans-serif',serif:'Georgia,Times New Roman,serif',mono:'Consolas,monospace',rounded:'Trebuchet MS,Arial,sans-serif'}[v]||DEFAULT_CONFIG.font;}
function hexToRgb(hex){const h=hex.replace('#','');return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)];}
function applyConfig(){const cfg=getConfig(); const app=document.getElementById('app'); if(!app)return; app.className=`app theme-${cfg.theme} mode-${cfg.mode}`; document.documentElement.style.setProperty('--primary',cfg.primary); document.documentElement.style.setProperty('--secondary',cfg.secondary); document.documentElement.style.setProperty('--font',fontValue(cfg.font)); document.documentElement.style.setProperty('--fs',cfg.fontSize+'px'); document.documentElement.style.setProperty('--panel',`rgba(255,255,255,${cfg.panelOpacity/100})`); const [r,g,b]=hexToRgb(cfg.mode==='oscuro'?'#02070a':'#122326'); document.documentElement.style.setProperty('--menu',`rgba(${r},${g},${b},${cfg.menuOpacity/100})`); ['appTitle','homeTitle'].forEach(id=>{const el=document.getElementById(id); if(el)el.textContent=cfg.title;}); document.title=cfg.title;}
function loadConfigForm(){const c=getConfig(); ['Title','Theme','Primary','Secondary','Font','FontSize','MenuOpacity','PanelOpacity','Mode'].forEach(k=>{const el=document.getElementById('cfg'+k); if(el)el.value=c[k.charAt(0).toLowerCase()+k.slice(1)];});}
function saveConfigFromForm(){saveConfig({title:cfgTitle.value.trim()||DEFAULT_CONFIG.title,theme:cfgTheme.value,primary:cfgPrimary.value,secondary:cfgSecondary.value,font:cfgFont.value,fontSize:+cfgFontSize.value,menuOpacity:+cfgMenuOpacity.value,panelOpacity:+cfgPanelOpacity.value,mode:cfgMode.value}); alert('Configuración guardada.');}
function resetConfig(){if(confirm('¿Restablecer configuración?')){writeJSON(STORE.CONFIG, DEFAULT_CONFIG); applyConfig(); loadConfigForm();}}
