function getSyncConfig(){return readJSON(STORE.SYNC,{peerId:'',dbUrl:'',lastSync:'',status:'Sin configurar'});}
function saveSyncConfig(cfg){writeJSON(STORE.SYNC,{...getSyncConfig(),...cfg}); loadSyncForm();}
function loadSyncForm(){const s=getSyncConfig(); if(syncDeviceId)syncDeviceId.value=getDeviceId(); if(syncPeerId)syncPeerId.value=s.peerId||''; if(syncDbUrl)syncDbUrl.value=s.dbUrl||''; if(syncStatus)syncStatus.value=navigator.onLine?'Online':'Sin conexión'; if(syncLast)syncLast.value=s.lastSync?formatDateTime(s.lastSync):'Nunca';}
function syncPath(){const s=getSyncConfig(); if(!s.dbUrl||!s.peerId)return null; const pair=[getDeviceId(),s.peerId].sort().join('_'); return s.dbUrl.replace(/\/$/,'') + '/rutas_maria_jesus/' + encodeURIComponent(pair) + '.json';}
function logSync(msg){if(syncLog)syncLog.textContent='['+new Date().toLocaleTimeString('es-ES')+'] '+msg+'\n'+syncLog.textContent;}
function pairDevice(){const peer=syncPeerId.value.trim().toUpperCase(); const db=syncDbUrl.value.trim(); if(!peer){alert('Introduce el ID del otro dispositivo.');return;} saveSyncConfig({peerId:peer,dbUrl:db}); logSync('Dispositivo emparejado: '+peer); alert('Emparejamiento guardado.');}
async function syncNow(auto=false){const url=syncPath(); if(!url){if(!auto)alert('Primero configura Firebase y empareja otro dispositivo.'); return;} if(!navigator.onLine){logSync('Sin internet. Se mantiene la copia local.'); return;} try{loadSyncForm(); logSync('Sincronizando...'); const remoteRes=await fetch(url,{cache:'no-store'}); const remote=remoteRes.ok?await remoteRes.json():null; const remoteRoutes=remote?.routes||[]; const merged=mergeRoutes(getRoutes(), remoteRoutes); saveRoutes(merged); const payload={updatedAt:nowISO(),devices:{[getDeviceId()]:{lastSeen:nowISO()}},routes:merged}; const put=await fetch(url,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); if(!put.ok)throw new Error('Firebase respondió: '+put.status); saveSyncConfig({lastSync:nowISO(),status:'Sincronizado'}); logSync('Sincronización completada. Registros: '+merged.length); }catch(e){logSync('Error de sincronización: '+e.message); if(!auto)alert('No se pudo sincronizar. Revisa la URL de Firebase y las reglas.');}}
function autoSyncOnStart(){setTimeout(()=>syncNow(true),900);}
window.addEventListener('online',()=>{loadSyncForm(); syncNow(true);});
window.addEventListener('offline',loadSyncForm);
